import { ChecklistItem, QuizQuestion, CrimeType, ScamAlert } from "@shared/api";

export const INITIAL_CRIME_TYPES: CrimeType[] = [
  {
    id: "phishing",
    name: "Phishing Scams",
    emoji: "🎣",
    description: "Fraudulent attempts to trick you into revealing sensitive information by impersonating trusted entities",
    examples: [
      "Fake banking emails requesting password verification",
      "Social media messages claiming your account is compromised",
      "Emails pretending to be from PayPal asking to confirm payment",
    ],
    signs: [
      "Urgent language requesting immediate action",
      "Generic greetings instead of your name",
      "Links that don't match the company domain",
      "Requests for personal or financial information",
      "Poor spelling and grammar",
    ],
    prevention: [
      "Never click links in unexpected emails",
      "Verify sender email addresses carefully",
      "Go directly to websites by typing the URL",
      "Check for HTTPS and padlock icon",
      "Enable two-factor authentication",
    ],
    tips: [
      { id: "1", title: "Hover Over Links", description: "Hover over links to see the actual URL before clicking", emoji: "🖱️" },
      { id: "2", title: "Check Email Headers", description: "Look at the full email header to verify the sender", emoji: "📋" },
      { id: "3", title: "Use Email Filters", description: "Enable spam filters and create rules for suspicious emails", emoji: "🔍" },
    ],
  },
  {
    id: "ransomware",
    name: "Ransomware Attacks",
    emoji: "🔒",
    description: "Malicious software that encrypts your files and demands payment for decryption",
    examples: [
      "Malware downloaded from suspicious websites",
      "Email attachments that contain encrypted threats",
      "Compromised USB drives containing malicious code",
    ],
    signs: [
      "Files become inaccessible or corrupted",
      "Strange file extensions on your documents",
      "Popup messages demanding payment",
      "System performance slows down dramatically",
      "Files are replaced with encrypted versions",
    ],
    prevention: [
      "Keep software and OS updated",
      "Use reliable antivirus software",
      "Backup important files regularly",
      "Be cautious with email attachments",
      "Don't download files from untrusted sources",
    ],
    tips: [
      { id: "1", title: "Regular Backups", description: "Maintain offline backups of critical data", emoji: "💾" },
      { id: "2", title: "Update Patches", description: "Install security patches as soon as they're available", emoji: "🔧" },
      { id: "3", title: "Network Segmentation", description: "Separate critical systems from public networks", emoji: "🔗" },
    ],
  },
  {
    id: "identity-theft",
    name: "Identity Theft",
    emoji: "👤",
    description: "Unauthorized use of your personal information to commit fraud",
    examples: [
      "Opening credit cards in your name",
      "Taking out loans using your identity",
      "Filing fraudulent tax returns",
      "Opening bank accounts illegally",
    ],
    signs: [
      "Credit card statements for accounts you didn't open",
      "Bills for services you never signed up for",
      "Calls from debt collectors about unknown debts",
      "Suspicious activity on your credit report",
      "Missing mail or receiving statements from unknown accounts",
    ],
    prevention: [
      "Monitor your credit reports regularly",
      "Use strong, unique passwords",
      "Shred sensitive documents",
      "Don't share SSN unnecessarily",
      "Check bank and credit statements monthly",
    ],
    tips: [
      { id: "1", title: "Credit Freeze", description: "Freeze your credit with major bureaus", emoji: "❄️" },
      { id: "2", title: "Identity Theft Protection", description: "Consider identity theft protection services", emoji: "🛡️" },
      { id: "3", title: "Dark Web Monitoring", description: "Monitor the dark web for your information", emoji: "🌐" },
    ],
  },
  {
    id: "upi-fraud",
    name: "UPI Fraud",
    emoji: "📱",
    description: "Fraudulent transactions using Unified Payments Interface in India",
    examples: [
      "QR code scams where wrong amount is transferred",
      "Fake UPI apps that steal bank details",
      "SMS-based scams requesting UPI approval",
      "Screen share fraud where attackers initiate false transactions",
    ],
    signs: [
      "Requests to share your UPI ID",
      "Unexpected UPI transaction requests",
      "Pop-ups asking for UPI credentials",
      "SMS messages with UPI links from unknown sources",
      "Screens showing wrong transaction amounts",
    ],
    prevention: [
      "Never share your UPI PIN or OTP",
      "Download apps only from official stores",
      "Verify recipient details before sending money",
      "Use transaction limits on your UPI",
      "Enable biometric authentication",
    ],
    tips: [
      { id: "1", title: "Verify QR Codes", description: "Always verify QR codes before scanning", emoji: "📲" },
      { id: "2", title: "Use UPI Lite", description: "Use UPI Lite for smaller transactions", emoji: "💰" },
      { id: "3", title: "Merchant Verification", description: "Verify merchant details in the app", emoji: "✓" },
    ],
  },
  {
    id: "deepfake",
    name: "Deepfake Scams",
    emoji: "🎭",
    description: "AI-generated videos or audio impersonating trusted individuals",
    examples: [
      "Video calls claiming to be family members asking for money",
      "Fake videos of executives requesting fund transfers",
      "Audio messages impersonating bosses requesting urgent actions",
      "Deepfake celebrity endorsement videos for fake products",
    ],
    signs: [
      "Unnatural blinking or lip movements",
      "Poor audio quality or lip-sync issues",
      "Unusual requests from known contacts",
      "Pressure to act urgently",
      "Requests made outside normal communication channels",
    ],
    prevention: [
      "Verify requests through alternative channels",
      "Ask security questions only known to them",
      "Be skeptical of video calls requesting money",
      "Use official communication channels",
      "Report suspicious content immediately",
    ],
    tips: [
      { id: "1", title: "Verification Call", description: "Call the person back using a trusted number", emoji: "☎️" },
      { id: "2", title: "Spot Artifacts", description: "Look for visual artifacts in videos", emoji: "👀" },
      { id: "3", title: "Report Deepfakes", description: "Report suspicious content to platforms", emoji: "🚨" },
    ],
  },
];

export const INITIAL_LIVE_ALERTS: ScamAlert[] = [
  {
    id: "alert-001",
    title: "Fake ICICI Bank App Warning",
    description: "Multiple reports of fake ICICI Bank app on Google Play Store that steals banking credentials",
    severity: "critical",
    type: "Phishing",
    targetAudience: "ICICI Bank Users",
    reportedCases: 1247,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    preventionTips: [
      "Only download from official Google Play Store",
      "Verify app developer is ICICI Bank Limited",
      "Check the blue verification badge",
      "Report suspicious apps immediately",
    ],
  },
  {
    id: "alert-002",
    title: "Amazon Gift Card Scam Surge",
    description: "Spike in SMS scams asking users to confirm purchases with gift cards",
    severity: "high",
    type: "SMS Fraud",
    targetAudience: "All Amazon Users",
    reportedCases: 3892,
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    preventionTips: [
      "Amazon never asks for payment via gift cards",
      "Never click links in unsolicited SMS",
      "Log in to your Amazon account directly",
      "Report phishing to Amazon security team",
    ],
  },
  {
    id: "alert-003",
    title: "Cryptocurrency Exchange Hack",
    description: "Major cryptocurrency exchange experiencing suspicious withdrawal activity",
    severity: "critical",
    type: "Account Compromise",
    targetAudience: "Crypto Investors",
    reportedCases: 5621,
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    preventionTips: [
      "Enable two-factor authentication",
      "Use hardware wallets for storage",
      "Never share seed phrases",
      "Monitor your account activity regularly",
    ],
  },
];

export const INITIAL_CHECKLIST_ITEMS: ChecklistItem[] = [
  {
    id: "account-security",
    category: "Account Security",
    title: "Secure Your Online Accounts",
    description: "Create strong passwords and enable two-factor authentication",
    steps: [
      "Create a unique password with 12+ characters including uppercase, lowercase, numbers, and symbols",
      "Enable two-factor authentication (2FA) on all important accounts",
      "Use a password manager to store credentials securely",
      "Review and update recovery options (email, phone number)",
      "Set up account activity alerts",
    ],
    priority: "high",
    estimatedTime: "30 minutes",
  },
  {
    id: "device-security",
    category: "Device Security",
    title: "Secure Your Devices",
    description: "Keep your devices updated and protected from malware",
    steps: [
      "Enable automatic updates for your operating system",
      "Install reputable antivirus and anti-malware software",
      "Turn on firewall protection",
      "Disable remote access features if not needed",
      "Encrypt your hard drive with BitLocker or FileVault",
    ],
    priority: "high",
    estimatedTime: "45 minutes",
  },
  {
    id: "email-security",
    category: "Email Security",
    title: "Protect Your Email Account",
    description: "Secure your primary email as it controls password recovery",
    steps: [
      "Create a strong, unique password for your email account",
      "Enable two-factor authentication",
      "Review connected applications and remove unknown ones",
      "Check forwarding rules for suspicious addresses",
      "Set up recovery phone number and alternate email",
    ],
    priority: "high",
    estimatedTime: "20 minutes",
  },
  {
    id: "wifi-security",
    category: "Network Security",
    title: "Secure Your WiFi Network",
    description: "Protect your home network from unauthorized access",
    steps: [
      "Change the default router password",
      "Use WPA3 encryption (or WPA2 if not available)",
      "Hide your SSID broadcast (optional)",
      "Enable router firewall",
      "Disable WPS (WiFi Protected Setup)",
    ],
    priority: "high",
    estimatedTime: "25 minutes",
  },
  {
    id: "financial-security",
    category: "Financial Security",
    title: "Secure Your Financial Accounts",
    description: "Protect your banking and payment information",
    steps: [
      "Enable fraud alerts with your bank",
      "Use virtual card numbers for online purchases",
      "Set up transaction limits on your accounts",
      "Monitor statements weekly for unauthorized transactions",
      "Register for credit monitoring services",
    ],
    priority: "high",
    estimatedTime: "35 minutes",
  },
];

export const INITIAL_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q1",
    question: "What is the most common way hackers steal passwords online?",
    options: ["Phishing emails and fake websites", "Breaking into data centers", "Hacking your WiFi router", "Using a microscope to see passwords"],
    correctAnswer: 0,
    explanation: "Phishing emails and fake websites are the most common methods used by hackers to trick users into revealing their passwords.",
    difficulty: "easy",
    category: "Phishing",
  },
  {
    id: "q2",
    question: "What does 2FA (Two-Factor Authentication) provide?",
    options: ["A second email address", "Protection using something you know AND something you have", "Double the storage space", "Two operating systems"],
    correctAnswer: 1,
    explanation: "2FA combines something you know (password) with something you have (phone, security key), making it much harder for attackers to gain access.",
    difficulty: "easy",
    category: "Account Security",
  },
  {
    id: "q3",
    question: "What is a characteristic of a strong password?",
    options: ["Your birth year and pet name", "A simple word like 'password123'", "12+ characters with uppercase, lowercase, numbers, and symbols", "Your username repeated twice"],
    correctAnswer: 2,
    explanation: "A strong password should have at least 12 characters and include a mix of uppercase letters, lowercase letters, numbers, and special characters.",
    difficulty: "easy",
    category: "Password Security",
  },
  {
    id: "q4",
    question: "What should you do if you receive a suspicious email?",
    options: ["Click the link to verify it's real", "Reply and ask for more information", "Don't click links, verify through official channels", "Forward it to everyone you know"],
    correctAnswer: 2,
    explanation: "Never click links in suspicious emails. Instead, go to the official website directly or call the organization.",
    difficulty: "easy",
    category: "Phishing",
  },
  {
    id: "q5",
    question: "What is ransomware?",
    options: ["A free antivirus software", "Malware that encrypts files and demands payment for decryption", "A backup service for your files", "A type of password manager"],
    correctAnswer: 1,
    explanation: "Ransomware is malicious software that encrypts your files, making them inaccessible, and then demands payment for the decryption key.",
    difficulty: "medium",
    category: "Malware",
  },
];
